/*
 * This source file was generated by the Gradle 'init' task
 */
package it.cs.unicam.progettomadeinitaly.app;

public class App {

    public static void main(String[] args) {

        // TODO JUNIT5 class with this stuff

        /**

         THIS IS OLD CODE AND WILL SUBSEQUENTIALLY DELETED IN THE NEXT ITERATIONS.


        RawProduct rp = new RawProduct(0,"Carlo Pisano",
                "Uva di MonteAlto"," Uva prodotta localmente nel comune di MonteAlto",
                "IGP", "Rossa", "Montano");

        TransformedProduct tp = new TransformedProduct(1, "Giuseppe Da Vinci", "Vino di MonteAlto",
                "Vino prodotto localmente nel comune di MonteAlto", "IGP", "Passerina");

        ProductPackage pp = new ProductPackage(2,"Alberto Pascal", "Esperienza natalizia",
                "La migliore Uva e il miglior vino di MonteAlto");

        TransformationProcess trap = new TransformationProcess(3,
                "Maturazione del uva", "Maturazione e processamento del uva"",
                "Giuseppe Da Vinci", null);

        // Setting transformation process for tp
        tp.setTransformationProcess(trap);

        // Adding products to pp
        pp.addProduct(rp);
        pp.addProduct(tp);

        // Products on sale

        RawProductOnSale rpos = new RawProductOnSale(4, "TestAuthor1", rp, 2.34f, 10);
        TransformedProductOnSale tpos = new TransformedProductOnSale(5, "TestAuthor2", tp, 12.89f, 12);
        ProductPackageOnSale ppos = new ProductPackageOnSale(6, "TestAuthor3", pp, 6.35f, 9);

        // Supply Chain Point test
        ISupplyChainPoint scp = new SupplyChainPoint
                (0, "Breaking Bad.srl", new Coordinate(0.0,0.0));

        boolean result1 = scp.addBusinessSpecialization(new ProductionSpecialization());
        boolean result2 = scp.addBusinessSpecialization(new TransformationSpecialization());
        boolean result3 = scp.addBusinessSpecialization(new DistributionSpecialization());
        boolean result4 = scp.addBusinessSpecialization(new ResaleSpecialization());

        System.out.println(result1 & result2 & result3 & result4);

        // Adding content

        boolean result5 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.PRODUCTION_SPECIALIZATION.getName()).addContent(rp);

        boolean resultX = scp.getBusinessSpecializationByName
                ("PRODUCTION_SPECIALIZATION").addContent(rp);
        boolean resultY = scp.getBusinessSpecializationByName
                ("production_specialization").addContent(rp);

        boolean result6 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.TRANSFORMATION_SPECIALIZATION.getName()).addContent(trap);
        boolean result7 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.TRANSFORMATION_SPECIALIZATION.getName()).addContent(tp);

        boolean result8 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.DISTRIBUTION_SPECIALIZATION.getName()).addContent(rp);
        boolean result9 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.DISTRIBUTION_SPECIALIZATION.getName()).addContent(tp);
        boolean result10 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.DISTRIBUTION_SPECIALIZATION.getName()).addContent(pp);

        boolean result11 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.RESALE_SPECIALIZATION.getName()).addContent(rpos);
        boolean result12 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.RESALE_SPECIALIZATION.getName()).addContent(tpos);
        boolean result13 = scp.getBusinessSpecializationByName
                (DefaultSpecializationNames.RESALE_SPECIALIZATION.getName()).addContent(ppos);

        System.out.println(result5 & resultX & result6 & result7 & result8 & result9
                & result10 & result11 & result12 & result13);

        ResaleSpecialization resaleGet = (ResaleSpecialization) scp.getBusinessSpecializationByName(
                DefaultSpecializationNames.RESALE_SPECIALIZATION.getName());

        // Raw test to see if products are what they are supposed to be
        List<ProductOnSale<? extends Product>> productsOnSale = resaleGet.getProductsOnSale();
        for (ProductOnSale<?> p : productsOnSale) {
            System.out.println("name: " + p.getName());
            if (p instanceof RawProductOnSale)
                System.out.println("meth: " + ((RawProductOnSale) p).getProductionMethod());
            if (p instanceof TransformedProductOnSale)
                System.out.println("proc: " + ((TransformedProductOnSale) p).getTransformationProcess());
            if (p instanceof ProductPackageOnSale)
                System.out.println("prodi: " + ((ProductPackageOnSale) p).getProducts());
        }

        */

    }
}

